CREATE TABLE Users (
    uid INT GENERATED BY DEFAULT AS IDENTITY,
    UNIQUE(uid),
    email VARCHAR UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    firstname VARCHAR(255) NOT NULL,
    lastname VARCHAR(255) NOT NULL,
    adrs VARCHAR(225) NOT NULL,
    balance FLOAT NOT NULL
);

CREATE TABLE Categories (
    name VARCHAR(50) NOT NULL PRIMARY KEY
);

CREATE TABLE Products (
    pid INT GENERATED BY DEFAULT AS IDENTITY,
    UNIQUE(pid),
    name VARCHAR(255) NOT NULL,
    description VARCHAR(300) NOT NULL,
    image VARCHAR(500) NOT NULL,
    price FLOAT NOT NULL,
    category VARCHAR(50) NOT NULL,
    creator_id INT NOT NULL REFERENCES Users(uid)
);

CREATE TABLE Sells (
    seller_id INT NOT NULL REFERENCES Users(uid),
    FOREIGN KEY (seller_id) REFERENCES Users(uid),
    pid INT NOT NULL REFERENCES Products(pid),
    FOREIGN KEY (pid) REFERENCES Products(pid),
    PRIMARY KEY (seller_id, pid),
    quantity INT NOT NULL
);

CREATE TABLE Reviews_Seller (
    rating INT NOT NULL CHECK (rating IN (0,1,2,3,4,5)),
    review VARCHAR(255) NOT NULL,
    user_id INT NOT NULL REFERENCES Users(uid),
    seller_id INT NOT NULL REFERENCES Users(uid),
    FOREIGN KEY (user_id) REFERENCES Users(uid),
    FOREIGN KEY (seller_id) REFERENCES Users(uid),
    PRIMARY KEY (user_id, seller_id),
    date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Reviews_Product (
    rating INT NOT NULL CHECK(rating IN (0,1,2,3,4,5)),
    review VARCHAR(255) NOT NULL,
    user_id INT NOT NULL REFERENCES Users(uid),
    product_id INT NOT NULL REFERENCES Products(pid), 
    FOREIGN KEY (user_id) REFERENCES Users(uid),
    FOREIGN KEY (product_id) REFERENCES Products(pid),
    PRIMARY KEY (user_id, product_id),
    date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC')
);

CREATE TABLE Orders (
    oid INT NOT NULL,
    product_id INT NOT NULL REFERENCES Products(pid),
    user_id INT NOT NULL REFERENCES Users(uid),
    seller_id INT NOT NULL REFERENCES Users(uid), 
    date timestamp without time zone NOT NULL DEFAULT (current_timestamp AT TIME ZONE 'UTC'),
    fulfilled BOOLEAN NOT NULL,
    num_items INT NOT NULL,
    PRIMARY KEY (oid, product_id)
);

CREATE TABLE HasInCart (
    user_id INT NOT NULL REFERENCES Users(uid),
    quantity INT NOT NULL,
    product_id  INT NOT NULL REFERENCES Products(pid),
    PRIMARY KEY (user_id, product_id),
    FOREIGN KEY (user_id) REFERENCES Users(uid),
    FOREIGN KEY (product_id) REFERENCES Products(pid),
    discount INT DEFAULT 0
);

CREATE TABLE Coupons(
    cid INT GENERATED BY DEFAULT AS IDENTITY,
    UNIQUE(cid),
    code VARCHAR(16) NOT NULL,
    discount INT NOT NULL,
    PRIMARY KEY (cid)
);